version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - php
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - D:/www:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/error.log:/var/log/nginx/error.log
    restart: always
    container_name: nginx
    networks:
      default:
        ipv4_address: 172.0.0.10

  php:
    build: ./php
    volumes:
      - D:/www:/var/www/html
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/config/php-fpm.d:/usr/local/etc/php-fpm.d 
    restart: always
    container_name: php
    extra_hosts:
      - "devpc-new.hxylt.cn:172.0.0.10"
    networks:
      default:
        ipv4_address: 172.0.0.20

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    container_name: mysql

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
      - ./redis/redis.log:/usr/local/redis/redis.log
    restart: always
    container_name: redis

networks:
  default:
    ipam:
      config:
        - subnet: 172.0.0.0/24
    
